spring.application.name=Tienda
#Se deefine el puerto por donde escucha el servidor web 
server.port=91
#Se define el formato de fecha/hora del log del servidor web 
logging.pattern.dateformat=hh:mm
#Se define no presentar el banner de SPRING en el log del servidor 
spring.main.banner-mode==off 
#Se evita el uso de cache en desarrollo en produccion si se debe usar 
spring.thymeleaf.cache=false 

spring.datasource.url=jdbc:mysql://localhost:3306/tienda_db
spring.datasource.username=root
spring.datasource.password=1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
firebase.bucket.name=techshop-a8349.firebasestorage.app
firebase.storage.path=XXXXXX
firebase.json.path=firebase
firebase.json.file=techshop-a8349-firebase-adminsdk-fbsvc-4803744618.json